### PR TITLE
Model Generation for Ur_New_Driver

### PR DESCRIPTION
**Pull request by ipa-nhg-ha**

### CODE REVIEW

**Comment by NadiaHG** [comment]
@ipa-nhg-ha please rename the project from NewUr_Driver to ur_driver and also the model file.

This requires probably the specific ur_msgs definition, please add a folder called msg and add the communication objects there.

Thanks!

**Comment by ipa-nhg-ha** [comment]
respected Miss Nadia

I have a confusion.Should i rename the project "NewUr_Driver" and upload it again with new requirements?

Thanks

________________________________

**Comment by NadiaHG** [comment]
yes, rename the project using eclipse and rename the model file also to ur_driver.ros.
Add a new folder for messages (called mgs) and add there the ur_msgs.ros file.

Open a terminal, cd to the Repository folder and "git status" , probably will say you have to add some files. And then git commit and git push


Thanks!

Nadia


------

M.Sc. Nadia HAMMOUDEH GARCÍA
Project Manager

Fraunhofer-Institut für Produktionstechnik und Automatisierung IPA
Robot and Assistive Systems Department
Group 326 - Software Engineering and System Integration

Nobelstraße 12, D-70569 Stuttgart (Germany)
Phone: +49 (0) 711-970-1067
Nadia.Hammoudeh.Garcia@ipa.fraunhofer.de
________________________________

**Comment by ipa-nhg-ha** [comment]
Respected Miss Naida

Thankyou.

Regards
Ameer Hamza
________________________________

**Comment by ipa-nhg-ha** [comment]
Respected Miss Nadia

I have upload the new project with required name and msg folder. Please check it.
I want to discuss one problem with you. Can i come?

Thanks and best regards
Ameer Hamza
________________________________

**Pull request closed without merging**
